name: linuxpatriot1776-custom
id: lp76-c 
stages:
- id: build
  base: ghcr.io/vanilla-os/desktop:main # Optionally, Replace this image URL with a different one i.e. nvidia:main, etc
  singlelayer: false
  labels:
    maintainer: self-maintained # Optionally, Replace this with your name
  args:
    DEBIAN_FRONTEND: noninteractive # Set the image environment as non-interactive
  
  # Commands to run first before building the modules
  runs:
    commands:
      - echo 'APT::Install-Recommends "1";' > /etc/apt/apt.conf.d/01norecommends

  modules:
  - name: init-setup
    type: shell
    commands:
    - lpkg --unlock
    - apt-get update

  # Put your custom actions behind this comment
  - name: install-packages 
    type: apt
    source:
      packages:
      - vim
      - gnome-tweaks
      - chrome-gnome-shell
      - libayatana-appindicator3-1
      - gir1.2-ayatanaappindicator3-0.1
      - gnome-shell-extension-appindicator
      - fastfetch
      - eza
      - python3-pyclipper
      - gir1.2-atk-1.0
      - gir1.2-freedesktop
      - gir1.2-gdkpixbuf-2.0
      - gir1.2-girepository-2.0
      - gir1.2-glib-2.0
      - gir1.2-gtk-3.0
      - gir1.2-harfbuzz-0.0
      - gir1.2-nm-1.0
      - gir1.2-pango-1.0
      - gnome-keyring
      - libbluetooth3
      - libgirepository-1.0-1
      - libharfbuzz-gobject0
      - libmm-glib0
      - libndp0
      - libnewt0.52
      - libnm0
      - libnma-common
      - libnma-gtk4-0
      - libnma0
      - libpangoxft-1.0-0
      - libpkcs11-helper1t64
      - libslang2
      - libteamdctl0
      - libxft2
      - lsb-release
      - network-manager
      - network-manager-openvpn
      - network-manager-openvpn-gnome
      - openvpn
      - p11-kit
      - p11-kit-modules
      - python3-aiohttp
      - python3-aiosignal
      - python3-async-timeout
      - python3-attr
      - python3-bcrypt
      - python3-cairo
      - python3-certifi
      - python3-cffi-backend
      - python3-chardet
      - python3-charset-normalizer
      - python3-cryptography
      - python3-dbus
      - python3-distro
      - python3-frozenlist
      - python3-gi
      - python3-gi-cairo
      - python3-gnupg
      - python3-idna
      - python3-importlib-metadata
      - python3-jaraco.classes
      - python3-jaraco.context
      - python3-jaraco.functools
      - python3-jeepney
      - python3-jinja2
      - python3-keyring
      - python3-markupsafe
      - python3-more-itertools
      - python3-multidict
      - python3-nacl
      - python3-openssl
      - python3-packaging
      - python3-pkg-resources
      - python3-requests
      - python3-secretstorage
      - python3-sentry-sdk
      - python3-urllib3
      - python3-yarl
      - python3-zipp
      - udev
      
  - name: install-deps-mullvad 
    type: apt
    source:
      packages:
      - libnss3-dev
      - libasound-dev
      
  - name: install-deps-proton 
    type: apt
    source:
      packages:
      - gir1.2-atk-1.0
      - gir1.2-freedesktop
      - gir1.2-gdkpixbuf-2.0
      - gir1.2-girepository-2.0
      - gir1.2-glib-2.0
      - gir1.2-gtk-3.0
      - gir1.2-harfbuzz-0.0
      - gir1.2-nm-1.0
      - gir1.2-pango-1.0
      - gnome-keyring
      - libbluetooth3
      - libgirepository-1.0-1
      - libharfbuzz-gobject0
      - libmm-glib0
      - libndp0
      - libnewt0.52
      - libnm0
      - libnma-common
      - libnma-gtk4-0
      - libnma0
      - libpangoxft-1.0-0
      - libpkcs11-helper1t64
      - libslang2
      - libteamdctl0
      - libxft2
      - lsb-release
      - network-manager
      - network-manager-openvpn
      - network-manager-openvpn-gnome
      - openvpn
      - p11-kit
      - p11-kit-modules
      - python3-aiohttp
      - python3-aiosignal
      - python3-async-timeout
      - python3-attr
      - python3-bcrypt
      - python3-cairo
      - python3-certifi
      - python3-cffi-backend
      - python3-chardet
      - python3-charset-normalizer
      - python3-cryptography
      - python3-dbus
      - python3-distro
      - python3-frozenlist
      - python3-gi
      - python3-gi-cairo
      - python3-gnupg
      - python3-idna
      - python3-importlib-metadata
      - python3-jaraco.classes
      - python3-jaraco.context
      - python3-jaraco.functools
      - python3-jeepney
      - python3-jinja2
      - python3-keyring
      - python3-markupsafe
      - python3-more-itertools
      - python3-multidict
      - python3-nacl
      - python3-openssl
      - python3-packaging
      - python3-pkg-resources
      - python3-requests
      - python3-secretstorage
      - python3-sentry-sdk
      - python3-urllib3
      - python3-yarl
      - python3-zipp
      - udev

      #- name: install-deps-windscribe-cli
      # type: apt
      #source:
      #packages:
      # - apt-transport-https
      #- gnupg

    - name: windscribe-pkg-download
       type: shell
      commands:
      - wget -O includes.container/deb-pkgs/windscribe.deb https://github.com/Windscribe/Desktop-App/releases/download/v2.10.8/windscribe_2.10.8_guinea_pig_amd64.deb
 
    #  - name: install-windscribe-cli 
    #type: apt
    #source:
    # packages:
    # - iptables
      
 - name: install-windscribe 
    type: apt
    source:
      packages:
      - iptables
      - libnetfilter-conntrack3
      - libnftnl11
      - libxcb-cursor0
      - libxcb-image0
      - libxcb-render-util0
      - libxcb-xkb1
      - net-tools
      - libip6tc2
      - libnfnetlink0
      - libopengl0
      - libxcb-icccm4
      - libxcb-keysyms1
      - libxcb-util1
      - libxkbcommon-x11-0
      
  - name: example-modules # Sample module demonstrating importing local and remote modules
    type: includes
    includes:
      - modules/50-install-debs.yml # Sample local module present in this repository
      - gh:vanilla-os/dev-image:main:modules/00-basics.yml # Sample GitHub remote module in the format: `gh:your-name/your-repo:branch:modules/file.yml`
      - https://raw.githubusercontent.com/Vanilla-OS/dev-image/main/modules/05-go.yml # Sample full URL remote module

  # Put your custom actions before this comment

  - name: set-image-name-abroot
    type: includes
    includes:
      - modules/80-set-image-abroot-config.yml

  - name: cleanup
    type: shell
    commands:
    - apt-get autoremove -y
    - apt-get clean
    - lpkg --lock

    #  - name: fsguard
    # type: fsguard
    #CustomFsGuard: false
    #FsGuardLocation: "/usr/sbin/FsGuard"
    #GenerateKey: true
    #FilelistPaths: ["/usr/bin"]
    #modules:
    # - name: remove-prev-fsguard
    #   type: shell
    #   commands:
    #     - rm -rf /FsGuard 
    #     - rm -f ./minisign.pub ./minisign.key 
    #     - chmod +x /usr/sbin/init

  - name: cleanup2
    type: shell
    commands:
      - rm -rf /tmp/*
      - rm -rf /var/tmp/*
      - rm -rf /sources
